use crate::domain::OduDomain;
use std::collections::HashMap;
use std::sync::OnceLock;

#[derive(Debug, Clone)]
pub struct OduMethodInfo {
    pub domain: OduDomain,
    pub method_id: u16,
    pub yoruba: &'static str,
    pub english: &'static str,
    pub aliases: &'static [&'static str],
}

pub static ODU_METHODS: &[(OduDomain, &[OduMethodInfo])] = &[
    (
        OduDomain::Ogbe,
        &[
            OduMethodInfo {
                domain: OduDomain::Ogbe,
                method_id: 0x0001,
                yoruba: "bere",
                english: "version",
                aliases: &["bere", "version"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogbe,
                method_id: 0x0002,
                yoruba: "args",
                english: "args",
                aliases: &["args", "àwọn_àríyànjú"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogbe,
                method_id: 0x0003,
                yoruba: "env",
                english: "env",
                aliases: &["env", "ayika"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogbe,
                method_id: 0x0004,
                yoruba: "cwd",
                english: "cwd",
                aliases: &["cwd", "ibi_isisiyi"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogbe,
                method_id: 0x0005,
                yoruba: "bi",
                english: "init",
                aliases: &["bi", "init"],
            },
        ],
    ),
    (
        OduDomain::Oyeku,
        &[
            OduMethodInfo {
                domain: OduDomain::Oyeku,
                method_id: 0x0101,
                yoruba: "jade",
                english: "halt",
                aliases: &["jade", "exit", "quit", "halt"],
            },
            OduMethodInfo {
                domain: OduDomain::Oyeku,
                method_id: 0x0102,
                yoruba: "sun",
                english: "wait",
                aliases: &["sun", "sleep", "wait"],
            },
            OduMethodInfo {
                domain: OduDomain::Oyeku,
                method_id: 0x0103,
                yoruba: "duro",
                english: "stop",
                aliases: &["duro", "stop"],
            },
            OduMethodInfo {
                domain: OduDomain::Oyeku,
                method_id: 0x0104,
                yoruba: "gbale",
                english: "gc",
                aliases: &["gbale", "gc"],
            },
        ],
    ),
    (
        OduDomain::Iwori,
        &[
            OduMethodInfo {
                domain: OduDomain::Iwori,
                method_id: 0x0201,
                yoruba: "bayi",
                english: "current",
                aliases: &["bayi", "now", "current"],
            },
            OduMethodInfo {
                domain: OduDomain::Iwori,
                method_id: 0x0202,
                yoruba: "akoko",
                english: "timestamp",
                aliases: &["akoko", "timestamp"],
            },
            OduMethodInfo {
                domain: OduDomain::Iwori,
                method_id: 0x0203,
                yoruba: "yipo",
                english: "iterate",
                aliases: &["yipo", "iterate"],
            },
            OduMethodInfo {
                domain: OduDomain::Iwori,
                method_id: 0x0204,
                yoruba: "pada",
                english: "return",
                aliases: &["pada", "return"],
            },
        ],
    ),
    (
        OduDomain::Odi,
        &[
            OduMethodInfo {
                domain: OduDomain::Odi,
                method_id: 0x0301,
                yoruba: "ka",
                english: "read",
                aliases: &["ka", "read"],
            },
            OduMethodInfo {
                domain: OduDomain::Odi,
                method_id: 0x0302,
                yoruba: "ko",
                english: "write",
                aliases: &["ko", "write"],
            },
            OduMethodInfo {
                domain: OduDomain::Odi,
                method_id: 0x0303,
                yoruba: "wa",
                english: "exists",
                aliases: &["wa", "exists"],
            },
            OduMethodInfo {
                domain: OduDomain::Odi,
                method_id: 0x0304,
                yoruba: "si",
                english: "open",
                aliases: &["si", "open"],
            },
            OduMethodInfo {
                domain: OduDomain::Odi,
                method_id: 0x0305,
                yoruba: "pa",
                english: "close",
                aliases: &["pa", "close"],
            },
            OduMethodInfo {
                domain: OduDomain::Odi,
                method_id: 0x0306,
                yoruba: "pa_iwe",
                english: "delete",
                aliases: &["pa_iwe", "delete", "pa"],
            },
        ],
    ),
    (
        OduDomain::Irosu,
        &[
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0401,
                yoruba: "fo",
                english: "println",
                aliases: &["fo", "println"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0402,
                yoruba: "so",
                english: "print",
                aliases: &["so", "print"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0403,
                yoruba: "gbo",
                english: "listen",
                aliases: &["gbo", "listen"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0404,
                yoruba: "gbo_nomba",
                english: "gbo_nomba",
                aliases: &["gbo_nomba"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0405,
                yoruba: "mo",
                english: "clear",
                aliases: &["mo", "clear"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0406,
                yoruba: "san",
                english: "flush",
                aliases: &["san", "flush"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0407,
                yoruba: "kigbe",
                english: "error",
                aliases: &["kigbe", "error"],
            },
            OduMethodInfo {
                domain: OduDomain::Irosu,
                method_id: 0x0408,
                yoruba: "ka",
                english: "read",
                aliases: &["ka", "read", "input"],
            },
        ],
    ),
    (
        OduDomain::Owonrin,
        &[
            OduMethodInfo {
                domain: OduDomain::Owonrin,
                method_id: 0x0501,
                yoruba: "nọmba",
                english: "random",
                aliases: &["nọmba", "pese", "random", "rand"],
            },
            OduMethodInfo {
                domain: OduDomain::Owonrin,
                method_id: 0x0502,
                yoruba: "yan_bool",
                english: "random_bool",
                aliases: &["yan_bool", "random_bool"],
            },
            OduMethodInfo {
                domain: OduDomain::Owonrin,
                method_id: 0x0503,
                yoruba: "yan_laarin",
                english: "range",
                aliases: &["yan_laarin", "range"],
            },
            OduMethodInfo {
                domain: OduDomain::Owonrin,
                method_id: 0x0504,
                yoruba: "paaro",
                english: "shuffle",
                aliases: &["paaro", "shuffle"],
            },
        ],
    ),
    (
        OduDomain::Obara,
        &[
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0601,
                yoruba: "fikun",
                english: "plus",
                aliases: &["fikun", "add", "plus"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0602,
                yoruba: "isodipupo",
                english: "times",
                aliases: &["isodipupo", "mul", "times"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0603,
                yoruba: "agbara",
                english: "pow",
                aliases: &["agbara", "pow"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0604,
                yoruba: "gbongbo",
                english: "sqrt",
                aliases: &["gbongbo", "sqrt"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0605,
                yoruba: "abs",
                english: "abs",
                aliases: &["abs"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0606,
                yoruba: "apapo",
                english: "sum",
                aliases: &["apapo", "sum"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0607,
                yoruba: "ile",
                english: "floor",
                aliases: &["ile", "floor"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0608,
                yoruba: "orule",
                english: "ceil",
                aliases: &["orule", "ceil"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0609,
                yoruba: "yika",
                english: "round",
                aliases: &["yika", "round"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x060A,
                yoruba: "iyoku",
                english: "modulo",
                aliases: &["iyoku", "modulo", "mod"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x060B,
                yoruba: "sin",
                english: "sin",
                aliases: &["sin"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x060C,
                yoruba: "cos",
                english: "cos",
                aliases: &["cos"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x060D,
                yoruba: "tan",
                english: "tan",
                aliases: &["tan"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x060E,
                yoruba: "asin",
                english: "asin",
                aliases: &["asin"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x060F,
                yoruba: "acos",
                english: "acos",
                aliases: &["acos"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0610,
                yoruba: "atan",
                english: "atan",
                aliases: &["atan"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0611,
                yoruba: "log",
                english: "log",
                aliases: &["log", "ln"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0612,
                yoruba: "log10",
                english: "log10",
                aliases: &["log10"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0613,
                yoruba: "exp",
                english: "exp",
                aliases: &["exp"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0614,
                yoruba: "aropin",
                english: "mean",
                aliases: &["aropin", "mean", "avg"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0615,
                yoruba: "nla_julo",
                english: "max",
                aliases: &["nla_julo", "max"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0616,
                yoruba: "kere_julo",
                english: "min",
                aliases: &["kere_julo", "min"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0617,
                yoruba: "pi",
                english: "pi",
                aliases: &["pi"],
            },
            OduMethodInfo {
                domain: OduDomain::Obara,
                method_id: 0x0618,
                yoruba: "e",
                english: "e",
                aliases: &["e"],
            },
        ],
    ),
    (
        OduDomain::Okanran,
        &[
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0701,
                yoruba: "sise",
                english: "check",
                aliases: &["sise", "assert", "verify", "check"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0702,
                yoruba: "ta",
                english: "ta",
                aliases: &["kigbe", "throw", "panic", "raise", "ta", "ku"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0703,
                yoruba: "dogba",
                english: "equals",
                aliases: &["dogba", "equals"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0704,
                yoruba: "beeni",
                english: "assert_true",
                aliases: &["beeni", "assert_true"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0705,
                yoruba: "yato",
                english: "assert_not_equal",
                aliases: &["yato", "assert_not_equal"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0706,
                yoruba: "beko",
                english: "assert_false",
                aliases: &["beko", "assert_false"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0707,
                yoruba: "ko_si",
                english: "assert_not_null",
                aliases: &["ko_si", "assert_not_null"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0708,
                yoruba: "ku_bi",
                english: "fatal",
                aliases: &["ku_bi", "fatal"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0709,
                yoruba: "ko_le_de_bi",
                english: "unreachable",
                aliases: &["ko_le_de_bi", "unreachable"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x070A,
                yoruba: "ko_ti_se_bi",
                english: "not_implemented",
                aliases: &["ko_ti_se_bi", "not_implemented"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x070B,
                yoruba: "owe",
                english: "proverb",
                aliases: &["owe", "proverb"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x070C,
                yoruba: "gbiyanju",
                english: "try_or",
                aliases: &["gbiyanju", "try_or"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x070D,
                yoruba: "wo",
                english: "debug",
                aliases: &["wo", "debug"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x070E,
                yoruba: "ku",
                english: "panic",
                aliases: &["ku", "panic"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x070F,
                yoruba: "ko_le_de",
                english: "unreachable_panic",
                aliases: &["ko_le_de", "unreachable_panic"],
            },
            OduMethodInfo {
                domain: OduDomain::Okanran,
                method_id: 0x0710,
                yoruba: "ko_ti_se",
                english: "not_implemented_panic",
                aliases: &["ko_ti_se", "not_implemented_panic"],
            },
        ],
    ),
    (
        OduDomain::Ogunda,
        &[
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0801,
                yoruba: "iwon",
                english: "apapo",
                aliases: &["iwon", "len", "count", "apapo"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0802,
                yoruba: "fi",
                english: "append",
                aliases: &["fi", "push", "append"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0803,
                yoruba: "mu",
                english: "pop",
                aliases: &["mu", "pop"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0804,
                yoruba: "yi_pada",
                english: "maapu",
                aliases: &["yi_pada", "yipada", "map", "maapu"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0805,
                yoruba: "yan",
                english: "ṣàjọ",
                aliases: &["yan", "filter", "sajo", "ṣàjọ"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0806,
                yoruba: "ṣẹ́kù",
                english: "fold",
                aliases: &["ṣẹ́kù", "seku", "din", "reduce", "fold"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0807,
                yoruba: "ge",
                english: "alloc",
                aliases: &["ge", "alloc"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0808,
                yoruba: "da",
                english: "create",
                aliases: &["da", "create"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0809,
                yoruba: "seda",
                english: "new_list",
                aliases: &["seda", "new_list"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x080A,
                yoruba: "seda_agbara",
                english: "with_capacity",
                aliases: &["seda_agbara", "with_capacity"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x080B,
                yoruba: "sofo",
                english: "is_empty",
                aliases: &["sofo", "is_empty"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x080C,
                yoruba: "pada",
                english: "reverse",
                aliases: &["pada", "reverse"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x080D,
                yoruba: "to",
                english: "sort",
                aliases: &["to", "sort"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x080E,
                yoruba: "dapo",
                english: "concat",
                aliases: &["dapo", "concat"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x080F,
                yoruba: "wa",
                english: "find",
                aliases: &["wa", "find"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0810,
                yoruba: "eyikeyi",
                english: "any",
                aliases: &["eyikeyi", "any"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0811,
                yoruba: "gbogbo",
                english: "all",
                aliases: &["gbogbo", "all"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0812,
                yoruba: "awon_kokoro",
                english: "keys",
                aliases: &["awon_kokoro", "keys"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0813,
                yoruba: "awon_iye",
                english: "values",
                aliases: &["awon_iye", "values"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0814,
                yoruba: "awon_nkan",
                english: "items",
                aliases: &["awon_nkan", "items"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0815,
                yoruba: "yo",
                english: "remove",
                aliases: &["yo", "remove"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0816,
                yoruba: "sise",
                english: "run",
                aliases: &["sise", "run"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0817,
                yoruba: "sise_ka",
                english: "run_read",
                aliases: &["sise_ka", "run_read"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0818,
                yoruba: "bere",
                english: "spawn",
                aliases: &["bere", "spawn"],
            },
            OduMethodInfo {
                domain: OduDomain::Ogunda,
                method_id: 0x0819,
                yoruba: "ayika",
                english: "get_env",
                aliases: &["ayika", "get_env"],
            },
        ],
    ),
    (
        OduDomain::Osa,
        &[
            OduMethodInfo {
                domain: OduDomain::Osa,
                method_id: 0x0901,
                yoruba: "sun",
                english: "sleep",
                aliases: &["sun", "sleep"],
            },
            OduMethodInfo {
                domain: OduDomain::Osa,
                method_id: 0x0902,
                yoruba: "gbogbo",
                english: "all",
                aliases: &["gbogbo", "all"],
            },
            OduMethodInfo {
                domain: OduDomain::Osa,
                method_id: 0x0903,
                yoruba: "sa",
                english: "spawn",
                aliases: &["sa", "spawn"],
            },
            OduMethodInfo {
                domain: OduDomain::Osa,
                method_id: 0x0904,
                yoruba: "duro",
                english: "await",
                aliases: &["duro", "await"],
            },
        ],
    ),
    (
        OduDomain::Ika,
        &[
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A01,
                yoruba: "gigun",
                english: "len",
                aliases: &["gigun", "len"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A02,
                yoruba: "ge",
                english: "slice",
                aliases: &["ge", "slice"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A03,
                yoruba: "so",
                english: "concat",
                aliases: &["so", "concat"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A04,
                yoruba: "oruko_html",
                english: "html_title",
                aliases: &["oruko_html", "html_title"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A05,
                yoruba: "tumo_html",
                english: "strip_html",
                aliases: &["tumo_html", "strip_html"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A06,
                yoruba: "nla",
                english: "uppercase",
                aliases: &["nla", "uppercase"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A07,
                yoruba: "kekere",
                english: "lowercase",
                aliases: &["kekere", "lowercase"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A08,
                yoruba: "wa",
                english: "find",
                aliases: &["wa", "find"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A09,
                yoruba: "ni",
                english: "has",
                aliases: &["ni", "has"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A0A,
                yoruba: "pin",
                english: "split",
                aliases: &["pin", "split"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A0B,
                yoruba: "dapo",
                english: "join",
                aliases: &["dapo", "join"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A0C,
                yoruba: "yi_pada",
                english: "replace",
                aliases: &["yi_pada", "replace"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A0D,
                yoruba: "pada",
                english: "reverse",
                aliases: &["pada", "reverse"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A0E,
                yoruba: "ge_lara",
                english: "substring",
                aliases: &["ge_lara", "substring"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A0F,
                yoruba: "tun",
                english: "repeat",
                aliases: &["tun", "repeat"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A10,
                yoruba: "bere",
                english: "starts_with",
                aliases: &["bere", "starts_with"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A11,
                yoruba: "pari",
                english: "ends_with",
                aliases: &["pari", "ends_with"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A12,
                yoruba: "ba_mu",
                english: "regex_match",
                aliases: &["ba_mu", "regex_match", "matches"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A13,
                yoruba: "wa_akoko",
                english: "regex_find",
                aliases: &["wa_akoko", "regex_find"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A14,
                yoruba: "wa_gbogbo",
                english: "regex_find_all",
                aliases: &["wa_gbogbo", "regex_find_all"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A15,
                yoruba: "ropo",
                english: "regex_replace",
                aliases: &["ropo", "regex_replace"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A16,
                yoruba: "yi_si_json",
                english: "encode",
                aliases: &["yi_si_json", "encode", "to_json"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A17,
                yoruba: "yi_pada_json",
                english: "decode",
                aliases: &["yi_pada_json", "decode", "from_json"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A18,
                yoruba: "bo",
                english: "url_encode",
                aliases: &["bo", "url_encode", "bo_asiri_url"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A19,
                yoruba: "titu_asiri_url",
                english: "url_decode",
                aliases: &["titu_asiri_url", "url_decode"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A1A,
                yoruba: "yi_si_csv",
                english: "to_csv",
                aliases: &["yi_si_csv", "to_csv"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A1B,
                yoruba: "yi_pada_csv",
                english: "from_csv",
                aliases: &["yi_pada_csv", "from_csv"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A1C,
                yoruba: "rope_new",
                english: "rope_new",
                aliases: &["rope_new"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A1D,
                yoruba: "rope_insert",
                english: "rope_insert",
                aliases: &["rope_insert"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A1E,
                yoruba: "rope_delete",
                english: "rope_delete",
                aliases: &["rope_delete"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A1F,
                yoruba: "rope_slice",
                english: "rope_slice",
                aliases: &["rope_slice"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A20,
                yoruba: "rope_len",
                english: "rope_len",
                aliases: &["rope_len"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A21,
                yoruba: "ge_trim",
                english: "trim",
                aliases: &["ge_trim", "trim"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A22,
                yoruba: "mo",
                english: "clean_html",
                aliases: &["mo", "clean_html"],
            },
            OduMethodInfo {
                domain: OduDomain::Ika,
                method_id: 0x0A23,
                yoruba: "wa_html",
                english: "html_query",
                aliases: &["wa_html", "html_query"],
            },
        ],
    ),
    (
        OduDomain::Oturupon,
        &[
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B01,
                yoruba: "yokuro",
                english: "minus",
                aliases: &["yokuro", "sub", "minus"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B02,
                yoruba: "pipin",
                english: "divide",
                aliases: &["pipin", "div", "divide"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B03,
                yoruba: "din",
                english: "sub_checked",
                aliases: &["din", "sub_checked"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B04,
                yoruba: "pin",
                english: "div_checked",
                aliases: &["pin", "div_checked"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B05,
                yoruba: "pin_odidi",
                english: "div_int",
                aliases: &["pin_odidi", "div_int"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B06,
                yoruba: "din_f",
                english: "sub_float",
                aliases: &["din_f", "sub_float"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B07,
                yoruba: "pin_f",
                english: "div_float",
                aliases: &["pin_f", "div_float"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B08,
                yoruba: "ku",
                english: "rem_checked",
                aliases: &["ku", "rem_checked"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B09,
                yoruba: "ku_euclidean",
                english: "rem_euclidean",
                aliases: &["ku_euclidean", "rem_euclidean"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B0A,
                yoruba: "dake",
                english: "neg_checked",
                aliases: &["dake", "neg_checked"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B0B,
                yoruba: "idakeji",
                english: "reciprocal",
                aliases: &["idakeji", "reciprocal"],
            },
            OduMethodInfo {
                domain: OduDomain::Oturupon,
                method_id: 0x0B0C,
                yoruba: "iyoku",
                english: "diff",
                aliases: &["iyoku", "diff"],
            },
        ],
    ),
    (
        OduDomain::Otura,
        &[
            OduMethodInfo {
                domain: OduDomain::Otura,
                method_id: 0x0C01,
                yoruba: "gba",
                english: "fetch",
                aliases: &["gba", "get", "fetch"],
            },
            OduMethodInfo {
                domain: OduDomain::Otura,
                method_id: 0x0C02,
                yoruba: "ran",
                english: "post",
                aliases: &["ran", "post"],
            },
            OduMethodInfo {
                domain: OduDomain::Otura,
                method_id: 0x0C03,
                yoruba: "de",
                english: "listen",
                aliases: &["de", "listen"],
            },
            OduMethodInfo {
                domain: OduDomain::Otura,
                method_id: 0x0C04,
                yoruba: "soro",
                english: "connect",
                aliases: &["soro", "connect"],
            },
            OduMethodInfo {
                domain: OduDomain::Otura,
                method_id: 0x0C05,
                yoruba: "pa",
                english: "close",
                aliases: &["pa", "close"],
            },
            OduMethodInfo {
                domain: OduDomain::Otura,
                method_id: 0x0C06,
                yoruba: "sayewo",
                english: "check_host",
                aliases: &["sayewo", "ṣàyẹ̀wò", "check_host"],
            },
        ],
    ),
    (
        OduDomain::Irete,
        &[
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D01,
                yoruba: "hash",
                english: "sha256",
                aliases: &["hash", "sha256"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D02,
                yoruba: "hmac",
                english: "hmac_sha256",
                aliases: &["hmac", "hmac_sha256"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D03,
                yoruba: "base64",
                english: "base64_encode",
                aliases: &["base64", "base64_encode"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D04,
                yoruba: "decode",
                english: "base64_decode",
                aliases: &["decode", "base64_decode"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D05,
                yoruba: "funpo",
                english: "compress",
                aliases: &["funpo", "compress"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D06,
                yoruba: "tu",
                english: "decompress",
                aliases: &["tu", "decompress"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D07,
                yoruba: "tu",
                english: "free",
                aliases: &["tu", "free"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D08,
                yoruba: "sha512",
                english: "sha512",
                aliases: &["sha512"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D09,
                yoruba: "hmac_verify",
                english: "hmac_verify",
                aliases: &["hmac_verify"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D0A,
                yoruba: "chacha20_encrypt",
                english: "encrypt",
                aliases: &["chacha20_encrypt", "encrypt", "di_pa"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D0B,
                yoruba: "chacha20_decrypt",
                english: "decrypt",
                aliases: &["chacha20_decrypt", "decrypt", "tu_pa"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D0C,
                yoruba: "ed25519_generate",
                english: "keypair",
                aliases: &["ed25519_generate", "keypair"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D0D,
                yoruba: "ed25519_sign",
                english: "sign",
                aliases: &["ed25519_sign", "sign", "fi_o"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D0E,
                yoruba: "ed25519_verify",
                english: "verify",
                aliases: &["ed25519_verify", "verify", "yewo_fo"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D0F,
                yoruba: "random_bytes",
                english: "random",
                aliases: &["random_bytes", "random"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D10,
                yoruba: "hex_encode",
                english: "hex",
                aliases: &["hex_encode", "hex"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D11,
                yoruba: "hex_decode",
                english: "unhex",
                aliases: &["hex_decode", "unhex"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D12,
                yoruba: "iwon_funpo",
                english: "ratio",
                aliases: &["iwon_funpo", "ratio"],
            },
            OduMethodInfo {
                domain: OduDomain::Irete,
                method_id: 0x0D13,
                yoruba: "sha256_hex",
                english: "sha256_hex",
                aliases: &["sha256_hex"],
            },
        ],
    ),
    (
        OduDomain::Ose,
        &[
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E01,
                yoruba: "bere",
                english: "init",
                aliases: &["bere", "init"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E02,
                yoruba: "pari",
                english: "end",
                aliases: &["pari", "end"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E03,
                yoruba: "gbile",
                english: "read_key",
                aliases: &["gbile", "read_key"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E04,
                yoruba: "apoti",
                english: "box",
                aliases: &["apoti", "box"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E05,
                yoruba: "ipinro",
                english: "section",
                aliases: &["ipinro", "section"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E06,
                yoruba: "ya",
                english: "draw",
                aliases: &["ya", "draw"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E07,
                yoruba: "nu",
                english: "clear",
                aliases: &["nu", "clear"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E08,
                yoruba: "wo",
                english: "debug",
                aliases: &["wo", "debug"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E09,
                yoruba: "gboran",
                english: "listen",
                aliases: &["gboran", "listen"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E0A,
                yoruba: "ipile",
                english: "layout",
                aliases: &["ipile", "layout"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E0B,
                yoruba: "emi",
                english: "mouse_on",
                aliases: &["emi", "ẹmí", "mouse_on"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E0C,
                yoruba: "pari_emi",
                english: "mouse_off",
                aliases: &["pari_emi", "pari_ẹmí", "mouse_off"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E0D,
                yoruba: "iwon",
                english: "size",
                aliases: &["iwon", "iwọn", "size"],
            },
            OduMethodInfo {
                domain: OduDomain::Ose,
                method_id: 0x0E0E,
                yoruba: "duro",
                english: "wait",
                aliases: &["duro", "wait"],
            },
        ],
    ),
    (
        OduDomain::Ofun,
        &[
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F01,
                yoruba: "le",
                english: "can",
                aliases: &["le", "can"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F02,
                yoruba: "da",
                english: "create",
                aliases: &["da", "create"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F03,
                yoruba: "pa",
                english: "delete",
                aliases: &["pa", "delete"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F04,
                yoruba: "iru",
                english: "type_of",
                aliases: &["iru", "type_of", "typeof"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F05,
                yoruba: "laaye",
                english: "is_alive",
                aliases: &["laaye", "is_alive"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F06,
                yoruba: "ju",
                english: "drop",
                aliases: &["ju", "drop"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F07,
                yoruba: "awon_agbara",
                english: "capabilities",
                aliases: &["awon_agbara", "capabilities"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F08,
                yoruba: "je",
                english: "is_type",
                aliases: &["je", "is_type"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F09,
                yoruba: "afiwe",
                english: "debug",
                aliases: &["afiwe", "debug", "inspect"],
            },
            OduMethodInfo {
                domain: OduDomain::Ofun,
                method_id: 0x0F0A,
                yoruba: "dbg",
                english: "dbg",
                aliases: &["dbg", "debug_print"],
            },
        ],
    ),
    (
        OduDomain::Cpu,
        &[
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1201,
                yoruba: "square",
                english: "square",
                aliases: &["square"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1202,
                yoruba: "cube",
                english: "cube",
                aliases: &["cube"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1203,
                yoruba: "double",
                english: "double",
                aliases: &["double"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1204,
                yoruba: "increment",
                english: "inc",
                aliases: &["increment", "inc"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1205,
                yoruba: "decrement",
                english: "dec",
                aliases: &["decrement", "dec"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1206,
                yoruba: "neg",
                english: "negate",
                aliases: &["neg", "negate"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1207,
                yoruba: "abs",
                english: "abs",
                aliases: &["abs"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1208,
                yoruba: "sqrt",
                english: "sqrt",
                aliases: &["sqrt"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1209,
                yoruba: "positive",
                english: "positive",
                aliases: &["positive"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x120A,
                yoruba: "negative",
                english: "negative",
                aliases: &["negative"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x120B,
                yoruba: "nonzero",
                english: "nonzero",
                aliases: &["nonzero"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x120C,
                yoruba: "even",
                english: "even",
                aliases: &["even"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x120D,
                yoruba: "odd",
                english: "odd",
                aliases: &["odd"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x120E,
                yoruba: "sum",
                english: "sum",
                aliases: &["sum"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x120F,
                yoruba: "product",
                english: "prod",
                aliases: &["product", "prod"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1210,
                yoruba: "min",
                english: "min",
                aliases: &["min"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1211,
                yoruba: "max",
                english: "max",
                aliases: &["max"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1212,
                yoruba: "configure",
                english: "configure",
                aliases: &["configure"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1213,
                yoruba: "threads",
                english: "num_threads",
                aliases: &["threads", "num_threads"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1214,
                yoruba: "par_sum",
                english: "par_sum",
                aliases: &["par_sum"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1215,
                yoruba: "par_map",
                english: "map",
                aliases: &["par_map", "map"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1216,
                yoruba: "par_filter",
                english: "filter",
                aliases: &["par_filter", "filter"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1217,
                yoruba: "par_reduce",
                english: "reduce",
                aliases: &["par_reduce", "reduce"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1218,
                yoruba: "par_sort",
                english: "sort",
                aliases: &["par_sort", "sort"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x1219,
                yoruba: "alloc_buffer",
                english: "alloc_buffer",
                aliases: &["alloc_buffer"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x121A,
                yoruba: "read_buffer",
                english: "read_buffer",
                aliases: &["read_buffer"],
            },
            OduMethodInfo {
                domain: OduDomain::Cpu,
                method_id: 0x121B,
                yoruba: "write_buffer",
                english: "write_buffer",
                aliases: &["write_buffer"],
            },
        ],
    ),
    (
        OduDomain::Gpu,
        &[
            OduMethodInfo {
                domain: OduDomain::Gpu,
                method_id: 0x1301,
                yoruba: "init",
                english: "init",
                aliases: &["init"],
            },
            OduMethodInfo {
                domain: OduDomain::Gpu,
                method_id: 0x1302,
                yoruba: "dispatch_pipeline",
                english: "dispatch",
                aliases: &["dispatch_pipeline", "dispatch"],
            },
            OduMethodInfo {
                domain: OduDomain::Gpu,
                method_id: 0x1303,
                yoruba: "sync",
                english: "sync",
                aliases: &["sync"],
            },
            OduMethodInfo {
                domain: OduDomain::Gpu,
                method_id: 0x1304,
                yoruba: "alloc_buffer",
                english: "alloc_buffer",
                aliases: &["alloc_buffer"],
            },
            OduMethodInfo {
                domain: OduDomain::Gpu,
                method_id: 0x1305,
                yoruba: "read_buffer",
                english: "read_buffer",
                aliases: &["read_buffer"],
            },
            OduMethodInfo {
                domain: OduDomain::Gpu,
                method_id: 0x1306,
                yoruba: "write_buffer",
                english: "write_buffer",
                aliases: &["write_buffer"],
            },
        ],
    ),
    (
        OduDomain::Storage,
        &[
            OduMethodInfo {
                domain: OduDomain::Storage,
                method_id: 0x1401,
                yoruba: "open",
                english: "open",
                aliases: &["open"],
            },
            OduMethodInfo {
                domain: OduDomain::Storage,
                method_id: 0x1402,
                yoruba: "get",
                english: "get",
                aliases: &["get"],
            },
            OduMethodInfo {
                domain: OduDomain::Storage,
                method_id: 0x1403,
                yoruba: "set",
                english: "set",
                aliases: &["set"],
            },
            OduMethodInfo {
                domain: OduDomain::Storage,
                method_id: 0x1404,
                yoruba: "delete",
                english: "del",
                aliases: &["delete", "del"],
            },
            OduMethodInfo {
                domain: OduDomain::Storage,
                method_id: 0x1405,
                yoruba: "compact",
                english: "compact",
                aliases: &["compact"],
            },
        ],
    ),
    (
        OduDomain::Sys,
        &[
            OduMethodInfo {
                domain: OduDomain::Sys,
                method_id: 0x1D01,
                yoruba: "num_cores",
                english: "cores",
                aliases: &["num_cores", "cores"],
            },
            OduMethodInfo {
                domain: OduDomain::Sys,
                method_id: 0x1D02,
                yoruba: "total_memory",
                english: "mem_total",
                aliases: &["total_memory", "mem_total"],
            },
            OduMethodInfo {
                domain: OduDomain::Sys,
                method_id: 0x1D03,
                yoruba: "available_memory",
                english: "mem_available",
                aliases: &["available_memory", "mem_available"],
            },
            OduMethodInfo {
                domain: OduDomain::Sys,
                method_id: 0x1D04,
                yoruba: "uptime",
                english: "uptime",
                aliases: &["uptime"],
            },
        ],
    ),
];

static METHOD_MAP: OnceLock<HashMap<(OduDomain, String), u16>> = OnceLock::new();
static METHOD_ID_MAP: OnceLock<HashMap<(u8, u16), &'static str>> = OnceLock::new();

fn init_maps() {
    let mut map = HashMap::new();
    let mut id_map = HashMap::new();
    for (domain, methods) in ODU_METHODS {
        for method in *methods {
            for alias in method.aliases {
                map.insert((*domain, alias.to_string()), method.method_id);
            }
            if let Some(domain_id) = domain.dispatch_id() {
                id_map.insert((domain_id, method.method_id), method.yoruba);
            }
        }
    }
    let _ = METHOD_MAP.set(map);
    let _ = METHOD_ID_MAP.set(id_map);
}

pub fn resolve_method_id(domain: OduDomain, method: &str) -> Option<u16> {
    if METHOD_MAP.get().is_none() {
        init_maps();
    }
    METHOD_MAP
        .get()
        .unwrap()
        .get(&(domain, method.to_string()))
        .copied()
}

pub fn method_name_from_id(domain_id: u8, method_id: u16) -> Option<&'static str> {
    if METHOD_ID_MAP.get().is_none() {
        init_maps();
    }
    METHOD_ID_MAP
        .get()
        .unwrap()
        .get(&(domain_id, method_id))
        .copied()
}

pub fn is_valid_odu_method(domain: &OduDomain, method: &str) -> bool {
    resolve_method_id(*domain, method).is_some()
}

pub fn odu_methods(domain: &OduDomain) -> Vec<&'static str> {
    ODU_METHODS
        .iter()
        .find(|(d, _)| d == domain)
        .map(|(_, methods)| {
            methods
                .iter()
                .flat_map(|m| m.aliases.iter().copied())
                .collect()
        })
        .unwrap_or_default()
}

pub fn get_method_info(domain: &OduDomain, method: &str) -> Option<OduMethodInfo> {
    ODU_METHODS
        .iter()
        .find(|(d, _)| d == domain)
        .and_then(|(_, methods)| {
            methods
                .iter()
                .find(|m| m.aliases.contains(&method))
                .cloned()
        })
}

pub fn all_odu_domains_with_methods() -> &'static [(OduDomain, &'static [OduMethodInfo])] {
    ODU_METHODS
}
