//! # Statement Transpilation
//!
//! Transpiles Ifá-Lang statements to Rust code.

use super::core::{RustTranspiler, std_domain_from_name};
use ifa_types::ast::*;

impl RustTranspiler {
    /// Transpile the entire program
    pub fn transpile_program(&mut self, program: &Program) -> String {
        self.prepare_imports(program);
        self.prepare_globals(program);
        let mut body = String::new();

        for stmt in &program.statements {
            body.push_str(&self.transpile_statement(stmt));
            body.push('\n');
        }

        let module_defs = if self.module_defs.is_empty() {
            String::new()
        } else {
            format!("{}\n", self.module_defs.join("\n"))
        };

        let uses = if self.uses.is_empty() {
            String::new()
        } else {
            self.uses.join("\n") + "\n"
        };

        // Build conditional imports
        let rand_import = if self.needs_rand {
            "use rand::Rng;\n"
        } else {
            ""
        };

        // Generate main function with async support if needed
        let main_fn = if self.has_async {
            "#[tokio::main]\nasync fn main()"
        } else {
            "fn main()"
        };

        format!(
            r#"//! Generated by Ifá-Lang Transpiler
//! Àṣẹ - May it be so

use std::collections::BTreeMap;
{rand_import}
{uses}
{module_defs}
/// Ifá Value type for dynamic typing
#[derive(Debug, Clone)]
pub enum IfaValue {{
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    List(Vec<IfaValue>),
    Map(BTreeMap<String, IfaValue>),
    Ptr(std::sync::Arc<std::sync::Mutex<IfaValue>>),
    Nil,
}}

impl PartialEq for IfaValue {{
    fn eq(&self, other: &Self) -> bool {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a == b,
            (IfaValue::Float(a), IfaValue::Float(b)) => a == b,
            (IfaValue::Str(a), IfaValue::Str(b)) => a == b,
            (IfaValue::Bool(a), IfaValue::Bool(b)) => a == b,
            (IfaValue::List(a), IfaValue::List(b)) => a == b,
            (IfaValue::Map(a), IfaValue::Map(b)) => a == b,
            (IfaValue::Ptr(a), IfaValue::Ptr(b)) => std::sync::Arc::ptr_eq(a, b),
            (IfaValue::Nil, IfaValue::Nil) => true,
            _ => false,
        }}
    }}
}}

impl PartialOrd for IfaValue {{
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.partial_cmp(b),
            (IfaValue::Float(a), IfaValue::Float(b)) => a.partial_cmp(b),
            (IfaValue::Str(a), IfaValue::Str(b)) => a.partial_cmp(b),
            _ => None,
        }}
    }}
}}

impl std::fmt::Display for IfaValue {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        match self {{
            IfaValue::Int(n) => write!(f, "{{}}", n),
            IfaValue::Float(n) => write!(f, "{{}}", n),
            IfaValue::Str(s) => write!(f, "{{}}", s),
            IfaValue::Bool(b) => write!(f, "{{}}", if *b {{ "òtítọ́" }} else {{ "èké" }}),
            IfaValue::Nil => write!(f, "àìsí"),
            IfaValue::List(l) => write!(f, "{{:?}}", l),
            IfaValue::Map(m) => write!(f, "{{:?}}", m),
            IfaValue::Ptr(_) => write!(f, "<ptr>"),
        }}
    }}
}}

impl IfaValue {{
    pub fn is_truthy(&self) -> bool {{
        match self {{
            IfaValue::Bool(b) => *b,
            IfaValue::Int(n) => *n != 0,
            // Spec: Float(0.0) is falsy; NaN is falsy; all other floats are truthy.
            IfaValue::Float(f) => *f != 0.0 && !f.is_nan(),
            IfaValue::Str(s) => !s.is_empty(),
            IfaValue::List(l) => !l.is_empty(),
            IfaValue::Map(m) => !m.is_empty(),
            IfaValue::Ptr(_) => true,
            IfaValue::Nil => false,
        }}
    }}

    pub fn pow(&self, other: &Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => {{
                if *b >= 0 {{
                    a.checked_pow(*b as u32).map(IfaValue::Int).unwrap_or_else(|| IfaValue::Float((*a as f64).powi(*b as i32)))
                }} else {{
                    IfaValue::Float((*a as f64).powi(*b as i32))
                }}
            }}
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a.powf(*b)),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float((*a as f64).powf(*b)),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a.powi(*b as i32)),
            _ => IfaValue::Nil,
        }}
    }}

    pub fn update_index(&mut self, idx: &IfaValue, op: fn(IfaValue, IfaValue) -> IfaValue, val: IfaValue) {{
        match self {{
            IfaValue::List(l) => {{
                if let IfaValue::Int(i) = idx {{
                    if *i >= 0 && (*i as usize) < l.len() {{
                        l[*i as usize] = op(l[*i as usize].clone(), val);
                    }}
                }}
            }}
            IfaValue::Map(m) => {{
                if let IfaValue::Str(k) = idx {{
                    if let Some(v) = m.get_mut(k) {{
                        *v = op(v.clone(), val);
                    }}
                }}
            }}
            _ => {{}}
        }}
    }}
}}

impl std::ops::Add for IfaValue {{
    type Output = Self;
    fn add(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.checked_add(b).map(IfaValue::Int).unwrap_or(IfaValue::Float(a as f64 + b as f64)),
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a + b),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float(a as f64 + b),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a + b as f64),
            (IfaValue::Str(a), IfaValue::Str(b)) => IfaValue::Str(format!("{{}}{{}}", a, b)),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Sub for IfaValue {{
    type Output = Self;
    fn sub(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.checked_sub(b).map(IfaValue::Int).unwrap_or(IfaValue::Float(a as f64 - b as f64)),
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a - b),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float(a as f64 - b),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a - b as f64),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Mul for IfaValue {{
    type Output = Self;
    fn mul(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.checked_mul(b).map(IfaValue::Int).unwrap_or(IfaValue::Float(a as f64 * b as f64)),
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a * b),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float(a as f64 * b),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a * b as f64),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Div for IfaValue {{
    type Output = Self;
    fn div(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => if b != 0 {{ IfaValue::Float(a as f64 / b as f64) }} else {{ IfaValue::Nil }},
            (IfaValue::Float(a), IfaValue::Float(b)) => if b != 0.0 {{ IfaValue::Float(a / b) }} else {{ IfaValue::Nil }},
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Rem for IfaValue {{
    type Output = Self;
    fn rem(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => if b != 0 {{ IfaValue::Int(a % b) }} else {{ IfaValue::Nil }},
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Neg for IfaValue {{
    type Output = Self;
    fn neg(self) -> Self {{
        match self {{
            IfaValue::Int(a) => IfaValue::Int(-a),
            IfaValue::Float(a) => IfaValue::Float(-a),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Not for IfaValue {{
    type Output = Self;
    fn not(self) -> Self {{
        IfaValue::Bool(!self.is_truthy())
    }}
}}

{main_fn} {{
{body}
    println!("\nÀṣẹ! (Success)");
}}
"#
        )
    }

    /// Transpile a single statement
    pub fn transpile_statement(&mut self, stmt: &Statement) -> String {
        let indent = self.indent_str();

        match stmt {
            Statement::VarDecl {
                name,
                value,
                visibility,
                ..
            } => {
                let m_name = self.mangle_identifier(name);
                let val = self.transpile_expression(value);
                if self.global_vars.contains(name) {
                    format!("{indent}__IFA_GLOBAL_{m_name}.with(|v| *v.borrow_mut() = {val});", indent = indent, m_name = m_name, val = val)
                } else if self.in_module {
                    format!("{indent}compile_error!(\"ifa build: class-level variables are not supported\");", indent = indent)
                } else {
                    format!(
                        "{}{}let mut {} = {};",
                        indent,
                        self.visibility_prefix(*visibility),
                        m_name,
                        val
                    )
                }
            }

            Statement::Const {
                name,
                value,
                visibility,
                ..
            } => {
                let m_name = self.mangle_identifier(name);
                let val = self.transpile_expression(value);
                if self.global_vars.contains(name) {
                    format!("{indent}__IFA_GLOBAL_{m_name}.with(|v| *v.borrow_mut() = {val});", indent = indent, m_name = m_name, val = val)
                } else if self.in_module {
                    format!("{indent}compile_error!(\"ifa build: class-level constants are not supported\");", indent = indent)
                } else {
                    format!(
                        "{}{}let {} = {};",
                        indent,
                        self.visibility_prefix(*visibility),
                        m_name,
                        val
                    )
                }
            }

            Statement::Assignment { target, value, .. } => {
                let val = self.transpile_expression(value);
                match target {
                    AssignTarget::Dereference(expr) => {
                        let ptr_expr = self.transpile_expression(expr);
                        format!("{indent}if let IfaValue::Ptr(p) = {ptr_expr} {{\n{indent}    let mut inner = p.lock().unwrap();\n{indent}    *inner = {val};\n{indent}}}")
                    }
                    _ => {
                        let target_str = self.transpile_assign_target(target);
                        if target_str.starts_with("__GLOBAL__") {
                            let m_name = target_str.strip_prefix("__GLOBAL__").unwrap();
                            format!("{indent}{}.with(|v| *v.borrow_mut() = {});", m_name, val, indent = indent)
                        } else {
                            format!("{indent}{} = {};", target_str, val, indent = indent)
                        }
                    }
                }
            }

            Statement::Instruction { call, .. } => {
                let call_str = self.transpile_odu_call(call);
                format!("{}{};", indent, call_str)
            }

            Statement::If {
                condition,
                then_body,
                else_body,
                ..
            } => {
                let cond = self.transpile_expression(condition);
                let mut result = format!("{}if ({}).is_truthy() {{\n", indent, cond);

                self.indent += 1;
                for s in then_body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;

                result.push_str(&format!("{}}}", indent));

                if let Some(else_stmts) = else_body {
                    result.push_str(" else {\n");
                    self.indent += 1;
                    for s in else_stmts {
                        result.push_str(&self.transpile_statement(s));
                        result.push('\n');
                    }
                    self.indent -= 1;
                    result.push_str(&format!("{}}}", indent));
                }

                result
            }

            Statement::While {
                condition, body, ..
            } => {
                let cond = self.transpile_expression(condition);
                let mut result = format!("{}while ({}).is_truthy() {{\n", indent, cond);

                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;

                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::For {
                var,
                iterable,
                body,
                ..
            } => {
                let iter = self.transpile_expression(iterable);
                let m_var = self.mangle_identifier(var);
                let mut result = format!("{}if let IfaValue::List(items) = {} {{\n", indent, iter);
                self.indent += 1;
                let indent2 = self.indent_str();
                result.push_str(&format!("{}for {} in items {{\n", indent2, m_var));

                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;

                result.push_str(&format!("{}}}\n", indent2));
                self.indent -= 1;
                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::Match {
                condition, arms, ..
            } => {
                let cond = self.transpile_expression(condition);
                let mut result = format!("{}let cond_val = {};\n", indent, cond);

                for (i, arm) in arms.iter().enumerate() {
                    let prefix = if i == 0 { "if" } else { "else if" };
                    let condition = match &arm.pattern {
                        MatchPattern::Literal(expr) => {
                            format!("cond_val == {}", self.transpile_expression(expr))
                        }
                        MatchPattern::Range { start, end } => {
                            let s = self.transpile_expression(start);
                            let e = self.transpile_expression(end);
                            format!("cond_val >= {} && cond_val <= {}", s, e)
                        }
                        MatchPattern::Wildcard => "true".to_string(),
                    };

                    result.push_str(&format!("{}{} {} {{\n", indent, prefix, condition));
                    self.indent += 1;
                    for s in &arm.body {
                        result.push_str(&self.transpile_statement(s));
                        result.push('\n');
                    }
                    self.indent -= 1;
                    result.push_str(&format!("{}}}\n", indent));
                }
                result.trim_end().to_string()
            }

            Statement::Return { value, .. } => {
                if let Some(v) = value {
                    format!(
                        "{}early_return = Some({}); return;",
                        indent,
                        self.transpile_expression(v)
                    )
                } else {
                    format!("{}return;", indent)
                }
            }

            Statement::EseDef {
                name,
                params,
                body,
                visibility,
                effects,
                ..
            } => {
                let vis = self.visibility_prefix(*visibility);
                let is_async = effects.contains(&ifa_types::ast::Effect::Async);
                let async_kw = if is_async {
                    self.has_async = true;
                    "async "
                } else {
                    ""
                };
                let params_str: Vec<String> = params
                    .iter()
                    .map(|p| format!("{}: IfaValue", p.name))
                    .collect();
                let mut result = format!(
                    "{}{}{}fn {}({}) -> IfaValue {{\n",
                    indent,
                    vis,
                    async_kw,
                    self.mangle_identifier(name),
                    params_str.join(", ")
                );

                self.indent += 1;
                result.push_str(&format!(
                    "{}let mut early_return: Option<IfaValue> = None;\n",
                    self.indent_str()
                ));
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                result.push_str(&format!(
                    "{}early_return.unwrap_or(IfaValue::Nil)\n",
                    self.indent_str()
                ));
                self.indent -= 1;

                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::OduDef { name, .. } => {
                // DESIGN DECISION (2026-04-07): Class-based OOP is formally removed from Ifá-Lang.
                // Both the AST interpreter and Bytecode VM already reject this syntax.
                // For native builds, we emit a hard compile_error! to prevent stale code execution.
                format!(
                    "{}compile_error!(\"Class/OOP syntax ('{}') is not supported. See ROADMAP.md §Phase 2 for migration to Map+Protocol design.\");",
                    indent, name
                )
            }

            Statement::Import { path, names, .. } => {
                if self.handle_import(path, names) {
                    format!("{}// import handled", indent)
                } else {
                    format!(
                        "{}compile_error!(\"ifa build: module '{:?}' not found or failed to parse\");",
                        indent, path
                    )
                }
            }

            Statement::Ase { .. } => {
                format!("{}std::process::exit(0);", indent)
            }

            Statement::Abo { .. } => {
                format!("{}// Strict mode directive", indent)
            }

            Statement::Taboo { source, target, .. } => {
                format!("{}// TABOO: {} cannot call {}", indent, source, target)
            }

            Statement::Ewo {
                condition, message, ..
            } => {
                let cond = self.transpile_expression(condition);
                let msg = message
                    .clone()
                    .unwrap_or_else(|| "Assertion failed".to_string());
                format!("{}assert(({}).is_truthy(), \"{}\");", indent, cond, msg)
            }

            Statement::Opon { size, .. } => {
                // Emit Rust constants from the #opon directive
                let (stack_limit, frame_limit) = match size.as_str() {
                    "kekere" => ("256", "64"),
                    "arinrin" => ("4_096", "512"),
                    "nla" => ("65_536", "4_096"),
                    "ailopin" => ("usize::MAX", "usize::MAX"),
                    _ => ("4_096", "512"), // default = arinrin
                };
                format!(
                    r#"{indent}// #opon {size} — memory constraints
{indent}const IFA_OPON_STACK_LIMIT: usize = {stack_limit};
{indent}const IFA_OPON_FRAME_LIMIT: usize = {frame_limit};"#,
                    indent = indent,
                    size = size,
                    stack_limit = stack_limit,
                    frame_limit = frame_limit,
                )
            }

            Statement::Expr { expr, .. } => {
                format!("{}{};", indent, self.transpile_expression(expr))
            }

            Statement::Ebo {
                offering,
                body: None,
                ..
            } => {
                let val = self.transpile_expression(offering);
                format!(
                    r#"{}{{
    // Ẹbọ: Reactive aspect initialized
    let _ebo_state = std::sync::Arc::new(std::sync::Mutex::new({}));
}}"#,
                    indent, val
                )
            }

            Statement::Ebo {
                offering,
                body: Some(body_stmts),
                ..
            } => {
                let _name = self.transpile_expression(offering);
                let mut result = format!("{}// Ẹbọ epoch: {{}};\n", indent);
                self.indent += 1;
                result.push_str(&format!(
                    "{}// Epoch begin: allocations scoped to this block\n",
                    indent
                ));
                for s in body_stmts {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                result.push_str(&format!("{}// Epoch end: memory released\n", indent));
                self.indent -= 1;
                result
            }

            Statement::Defer { body, .. } => {
                let mut result = format!("{}defer!(|| {{\n", indent);
                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;
                result.push_str(&format!("{}}})", indent));
                result
            }

            Statement::Ailewu { body, .. } => {
                let mut result = format!("{}unsafe {{\n", indent);
                result.push_str(&format!(
                    "{}    // Àìléwu: Dangerous operations ahead\n",
                    indent
                ));
                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;
                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::Yield { duration, .. } => {
                let dur = self.transpile_expression(duration);
                format!(
                    r#"{indent}{{
{indent}    let __ifa_yield_duration = {dur};
{indent}    match __ifa_yield_duration {{
{indent}        IfaValue::Int(micros) if micros > 0 => std::thread::sleep(std::time::Duration::from_micros(micros as u64)),
{indent}        IfaValue::Int(_) => (), // jowo 0: yield immediately / no duration hint
{indent}        _ => eprintln!("Runtime Error: Yield duration must be an Int (microseconds)"),
{indent}    }}
{indent}}}"#,
                    indent = indent,
                    dur = dur
                )
            }

            Statement::Update { target, op, value, .. } => {
                let op_fn = match op {
                    UpdateOp::AddAssign => "std::ops::Add::add",
                    UpdateOp::SubAssign => "std::ops::Sub::sub",
                    UpdateOp::MulAssign => "std::ops::Mul::mul",
                    UpdateOp::DivAssign => "std::ops::Div::div",
                    UpdateOp::ModAssign => "std::ops::Rem::rem",
                };
                let val_expr = match value {
                    Some(expr) => self.transpile_expression(expr),
                    None => "IfaValue::Int(1)".to_string(), // ++ or --
                };

                match target {
                    AssignTarget::Variable(name) => {
                        let m_name = self.mangle_identifier(name);
                        if self.global_vars.contains(name) {
                            format!("{indent}__IFA_GLOBAL_{name}.with(|v| {{\n{indent}    let new_val = {op_fn}(v.borrow().clone(), {val});\n{indent}    *v.borrow_mut() = new_val;\n{indent}}});", indent=indent, name=m_name, op_fn=op_fn, val=val_expr)
                        } else {
                            format!("{indent}{name} = {op_fn}({name}.clone(), {val});", indent=indent, name=m_name, op_fn=op_fn, val=val_expr)
                        }
                    }
                    AssignTarget::Index { name, index } => {
                        let name_mangled = self.mangle_identifier(name);
                        let idx_expr = self.transpile_expression(index);
                        format!("{indent}{name}.update_index(&{idx}, {op_fn}, {val});", indent=indent, name=name_mangled, idx=idx_expr, op_fn=op_fn, val=val_expr)
                    }
                    AssignTarget::Dereference(expr) => {
                        let ptr_expr = self.transpile_expression(expr);
                        format!("{indent}if let IfaValue::Ptr(p) = {ptr_expr} {{\n{indent}    let mut inner = p.lock().unwrap();\n{indent}    let new_val = {op_fn}(inner.clone(), {val});\n{indent}    *inner = new_val;\n{indent}}}", indent=indent, ptr_expr=ptr_expr, op_fn=op_fn, val=val_expr)
                    }
                }
            }

            Statement::Try { try_body, catch_var, catch_body, finally_body, .. } => {
                let mut result = format!("{}let _try_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {{\n", indent);
                self.indent += 1;
                for s in try_body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;
                result.push_str(&format!("{}}}));\n", indent));

                result.push_str(&format!("{}if let Err(_err) = _try_result {{\n", indent));
                self.indent += 1;
                result.push_str(&format!("{}let {} = if let Some(ifa_val) = _err.downcast_ref::<IfaValue>() {{ ifa_val.clone() }} else {{ IfaValue::Str(format!(\"{{:?}}\", _err)) }};\n", self.indent_str(), self.mangle_identifier(catch_var)));
                for s in catch_body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;
                result.push_str(&format!("{}}}\n", indent));

                if let Some(finally_stmts) = finally_body {
                    result.push_str(&format!("{}// Finally block\n", indent));
                    result.push_str(&format!("{}let _ = || {{\n", indent));
                    self.indent += 1;
                    for s in finally_stmts {
                        result.push_str(&self.transpile_statement(s));
                        result.push('\n');
                    }
                    self.indent -= 1;
                    result.push_str(&format!("{}}}();\n", indent));
                }
                result
            }

            // K1: break/continue — native Rust keywords; exact transpilation
            Statement::Break { .. } => format!("{}break;", indent),
            Statement::Continue { .. } => format!("{}continue;", indent),

            Statement::Throw { value, .. } => {
                let val_str = self.transpile_expression(value);
                format!("{}std::panic::panic_any({});", indent, val_str)
            }
        }
    }

    /// Transpile assignment target
    pub fn transpile_assign_target(&mut self, target: &AssignTarget) -> String {
        match target {
            AssignTarget::Variable(name) => {
                let m_name = self.mangle_identifier(name);
                if self.global_vars.contains(name) {
                    // This generates a string that needs special handling in Statement::Assignment,
                    // but transpile_assign_target normally just returns a string to be suffixed with ` = value;`.
                    // Wait, this is tricky. `VAR.with(|v| *v.borrow_mut()) = val;` is valid Rust if `borrow_mut()` returns a `RefMut`.
                    // Yes, `*v.borrow_mut() = val;` is valid! So returning `*VAR.with(|v| v.borrow_mut())` doesn't work directly because `RefMut` doesn't live long enough for `*foo = bar`. 
                    // Actually `VAR.with(|v| *v.borrow_mut() = val)` is what we need.
                    // Let me change how Statement::Assignment uses this.
                    // Actually, if we return `__GLOBAL__m_name` we can intercept it in `Statement::Assignment`.
                    format!("__GLOBAL____IFA_GLOBAL_{}", m_name)
                } else {
                    m_name
                }
            }
            AssignTarget::Index { name, index } => {
                format!(
                    "{}[{}]",
                    self.mangle_identifier(name),
                    self.transpile_expression(index)
                )
            }
            AssignTarget::Dereference(_) => {
                "/* Handled directly in assignment logic */".to_string()
            }
        }
    }

    fn prepare_imports(&mut self, program: &Program) {
        for stmt in &program.statements {
            if let Statement::Import { path, names, .. } = stmt {
                self.handle_import(path, names);
            }
        }
    }

    fn prepare_globals(&mut self, program: &Program) {
        // Collect root-level variables and emit thread_local! definitions initialized to Nil.
        for stmt in &program.statements {
            match stmt {
                Statement::VarDecl { name, .. } | Statement::Const { name, .. } => {
                    // Assuming root level if we are not inside an `odu` block or function
                    if !self.in_module {
                        let m_name = self.mangle_identifier(name);
                        self.global_vars.insert(name.clone());
                        self.module_defs.push(format!(
                            "thread_local! {{ static __IFA_GLOBAL_{}: std::cell::RefCell<IfaValue> = std::cell::RefCell::new(IfaValue::Nil); }}",
                            m_name
                        ));
                    }
                }
                _ => {}
            }
        }
    }

    fn handle_import(&mut self, path: &[String], names: &Option<Vec<String>>) -> bool {
        let is_std = path.first().map(|p| p == "std").unwrap_or(false);
        if is_std {
            let domain_name = path.last().cloned().unwrap_or_default();
            if let Some(domain) = std_domain_from_name(&domain_name) {
                if let Some(names) = names {
                    for name in names {
                        self.std_named.insert(name.clone(), domain);
                    }
                } else {
                    let module_name = path.last().cloned().unwrap_or_else(|| "module".into());
                    self.std_modules.insert(module_name, domain);
                }
            }
            return true;
        }

        // Custom module resolution
        if let Some(base_path) = &self.base_path {
            let mut file_path = base_path.clone();
            for part in path {
                file_path.push(part);
            }
            file_path.set_extension("ifa");

            let module_name = path.last().cloned().unwrap_or_else(|| "module".into());
            if self.parsed_modules.contains(&module_name) {
                return true; // Already imported
            }

            if let Ok(source) = std::fs::read_to_string(&file_path) {
                if let Ok(program) = ifa_parser::parse(&source) {
                    self.parsed_modules.insert(module_name.clone());
                    self.module_aliases.insert(module_name.clone());
                    
                    let mut sub = RustTranspiler::new();
                    sub.base_path = self.base_path.clone();
                    sub.parsed_modules = self.parsed_modules.clone();
                    
                    let code = sub.transpile_module(&program, &module_name);
                    
                    self.has_async |= sub.has_async;
                    self.needs_tokio |= sub.needs_tokio;
                    self.needs_reqwest |= sub.needs_reqwest;
                    self.needs_rand |= sub.needs_rand;
                    
                    for pm in sub.parsed_modules {
                        self.parsed_modules.insert(pm);
                    }
                    for (name, content) in sub.external_modules {
                        self.external_modules.insert(name, content);
                    }
                    
                    self.external_modules.insert(format!("{}.rs", module_name), code);
                    self.module_defs.push(format!("pub mod {};", module_name));
                    return true;
                }
            }
        }
        false
    }

    pub fn transpile_module(&mut self, program: &Program, _module_name: &str) -> String {
        self.in_module = true;
        self.prepare_imports(program);
        self.prepare_globals(program);
        let mut body = String::new();
        for stmt in &program.statements {
            body.push_str(&self.transpile_statement(stmt));
            body.push('\n');
        }
        let sub_modules = if self.module_defs.is_empty() { String::new() } else { self.module_defs.join("\n") };
        
        format!("use crate::IfaValue;\n{}\n{}", sub_modules, body)
    }
}
