[package]
name = "ifa-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "CLI for Ifá-Lang - The Yoruba Programming Language"

[[bin]]
name = "ifa"
path = "src/main.rs"

[dependencies]
ifa-vm = { path = "../ifa-vm", default-features = false }
ifa-parser = { path = "../ifa-parser" }
ifa-std = { path = "../ifa-std", default-features = false }
ifa-babalawo = { path = "../ifa-babalawo" }
ifa-fmt = { path = "../ifa-fmt" }
ifa-sandbox = { path = "../ifa-sandbox" }
ifa-types = { path = "../ifa-types", features = ["vm"] }
ifa-infra = { path = "../ifa-infra", features = ["persistence"] }

# CLI
clap.workspace = true

# Error handling
eyre.workspace = true
color-eyre.workspace = true

# Serialization (for ifa.toml)
serde.workspace = true
serde_json.workspace = true
lsp-server = "0.7"
lsp-types = "0.94"
toml = "0.8"

# Async runtime
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

# Datetime
chrono.workspace = true

# Self Update
ifa-installer-core = { path = "../ifa-installer-core" }
uuid = { workspace = true }
ureq = { version = "2.9", features = ["json"] }
flate2 = "1.0"
tar = "0.4"
ring.workspace = true

# System info for memory tracking
sysinfo = "0.30"
ifa-compiler = { version = "1.3.0", path = "../ifa-compiler" }


dirs = "5.0"
rayon.workspace = true


[features]
default = ["full"]
full = [
    "ifa-std/full", 
    "ifa-vm/std", "ifa-vm/sysinfo", "ifa-vm/parallel", "ifa-vm/gpu", "ifa-vm/compiler", 
    "ifa-types/vm", 
    "ifa-infra/persistence"
]
minimal = [
    "ifa-vm/std", "ifa-vm/compiler", 
    "ifa-types/vm"
]
