//! # Statement Transpilation
//!
//! Transpiles Ifá-Lang statements to Rust code.

use super::core::{RustTranspiler, std_domain_from_name};
use crate::ast::*;

impl RustTranspiler {
    /// Transpile the entire program
    pub fn transpile_program(&mut self, program: &Program) -> String {
        self.prepare_imports(program);
        let mut body = String::new();

        for stmt in &program.statements {
            body.push_str(&self.transpile_statement(stmt));
            body.push('\n');
        }

        let module_defs = if self.module_defs.is_empty() {
            String::new()
        } else {
            format!("{}\n", self.module_defs.join("\n"))
        };

        let uses = if self.uses.is_empty() {
            String::new()
        } else {
            self.uses.join("\n") + "\n"
        };

        // Build conditional imports
        let rand_import = if self.needs_rand {
            "use rand::Rng;\n"
        } else {
            ""
        };

        // Generate main function with async support if needed
        let main_fn = if self.has_async {
            "#[tokio::main]\nasync fn main()"
        } else {
            "fn main()"
        };

        format!(
            r#"//! Generated by Ifá-Lang Transpiler
//! Àṣẹ - May it be so

use std::collections::HashMap;
{rand_import}
{uses}
{module_defs}
/// Ifá Value type for dynamic typing
#[derive(Debug, Clone, PartialEq, PartialOrd)]
pub enum IfaValue {{
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    List(Vec<IfaValue>),
    Map(HashMap<String, IfaValue>),
    Nil,
}}

impl std::fmt::Display for IfaValue {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        match self {{
            IfaValue::Int(n) => write!(f, "{{}}", n),
            IfaValue::Float(n) => write!(f, "{{}}", n),
            IfaValue::Str(s) => write!(f, "{{}}", s),
            IfaValue::Bool(b) => write!(f, "{{}}", if *b {{ "òtítọ́" }} else {{ "èké" }}),
            IfaValue::Nil => write!(f, "àìsí"),
            IfaValue::List(l) => write!(f, "{{:?}}", l),
            IfaValue::Map(m) => write!(f, "{{:?}}", m),
        }}
    }}
}}

impl IfaValue {{
    pub fn is_truthy(&self) -> bool {{
        match self {{
            IfaValue::Bool(b) => *b,
            IfaValue::Int(n) => *n != 0,
            // Spec: Float(0.0) is falsy; NaN is falsy; all other floats are truthy.
            IfaValue::Float(f) => *f != 0.0 && !f.is_nan(),
            IfaValue::Str(s) => !s.is_empty(),
            IfaValue::List(l) => !l.is_empty(),
            IfaValue::Map(m) => !m.is_empty(),
            IfaValue::Nil => false,
        }}
    }}
}}

impl std::ops::Add for IfaValue {{
    type Output = Self;
    fn add(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.checked_add(b).map(IfaValue::Int).unwrap_or(IfaValue::Float(a as f64 + b as f64)),
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a + b),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float(a as f64 + b),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a + b as f64),
            (IfaValue::Str(a), IfaValue::Str(b)) => IfaValue::Str(format!("{{}}{{}}", a, b)),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Sub for IfaValue {{
    type Output = Self;
    fn sub(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.checked_sub(b).map(IfaValue::Int).unwrap_or(IfaValue::Float(a as f64 - b as f64)),
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a - b),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float(a as f64 - b),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a - b as f64),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Mul for IfaValue {{
    type Output = Self;
    fn mul(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => a.checked_mul(b).map(IfaValue::Int).unwrap_or(IfaValue::Float(a as f64 * b as f64)),
            (IfaValue::Float(a), IfaValue::Float(b)) => IfaValue::Float(a * b),
            (IfaValue::Int(a), IfaValue::Float(b)) => IfaValue::Float(a as f64 * b),
            (IfaValue::Float(a), IfaValue::Int(b)) => IfaValue::Float(a * b as f64),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Div for IfaValue {{
    type Output = Self;
    fn div(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => if b != 0 {{ IfaValue::Float(a as f64 / b as f64) }} else {{ IfaValue::Nil }},
            (IfaValue::Float(a), IfaValue::Float(b)) => if b != 0.0 {{ IfaValue::Float(a / b) }} else {{ IfaValue::Nil }},
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Rem for IfaValue {{
    type Output = Self;
    fn rem(self, other: Self) -> Self {{
        match (self, other) {{
            (IfaValue::Int(a), IfaValue::Int(b)) => if b != 0 {{ IfaValue::Int(a % b) }} else {{ IfaValue::Nil }},
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Neg for IfaValue {{
    type Output = Self;
    fn neg(self) -> Self {{
        match self {{
            IfaValue::Int(a) => IfaValue::Int(-a),
            IfaValue::Float(a) => IfaValue::Float(-a),
            _ => IfaValue::Nil,
        }}
    }}
}}

impl std::ops::Not for IfaValue {{
    type Output = Self;
    fn not(self) -> Self {{
        IfaValue::Bool(!self.is_truthy())
    }}
}}

{main_fn} {{
{body}
    println!("\nÀṣẹ! (Success)");
}}
"#
        )
    }

    /// Transpile a single statement
    pub fn transpile_statement(&mut self, stmt: &Statement) -> String {
        let indent = self.indent_str();

        match stmt {
            Statement::VarDecl {
                name,
                value,
                visibility,
                ..
            } => {
                let m_name = self.mangle_identifier(name);
                let val = self.transpile_expression(value);
                if self.in_module {
                    format!(
                        "{}compile_error!(\"ifa build: module-level variables are not supported yet\");",
                        indent
                    )
                } else {
                    format!(
                        "{}{}let mut {} = {};",
                        indent,
                        self.visibility_prefix(*visibility),
                        m_name,
                        val
                    )
                }
            }

            Statement::Const {
                name,
                value,
                visibility,
                ..
            } => {
                let m_name = self.mangle_identifier(name);
                let val = self.transpile_expression(value);
                // Use let (immutable) for constants in transpiled code
                if self.in_module {
                    format!(
                        "{}compile_error!(\"ifa build: module-level constants are not supported yet\");",
                        indent
                    )
                } else {
                    format!(
                        "{}{}let {} = {};",
                        indent,
                        self.visibility_prefix(*visibility),
                        m_name,
                        val
                    )
                }
            }

            Statement::Assignment { target, value, .. } => {
                let target_str = self.transpile_assign_target(target);
                let val = self.transpile_expression(value);
                format!("{}{} = {};", indent, target_str, val)
            }

            Statement::Instruction { call, .. } => {
                let call_str = self.transpile_odu_call(call);
                format!("{}{};", indent, call_str)
            }

            Statement::If {
                condition,
                then_body,
                else_body,
                ..
            } => {
                let cond = self.transpile_expression(condition);
                let mut result = format!("{}if ({}).is_truthy() {{\n", indent, cond);

                self.indent += 1;
                for s in then_body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;

                result.push_str(&format!("{}}}", indent));

                if let Some(else_stmts) = else_body {
                    result.push_str(" else {\n");
                    self.indent += 1;
                    for s in else_stmts {
                        result.push_str(&self.transpile_statement(s));
                        result.push('\n');
                    }
                    self.indent -= 1;
                    result.push_str(&format!("{}}}", indent));
                }

                result
            }

            Statement::While {
                condition, body, ..
            } => {
                let cond = self.transpile_expression(condition);
                let mut result = format!("{}while ({}).is_truthy() {{\n", indent, cond);

                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;

                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::For {
                var,
                iterable,
                body,
                ..
            } => {
                let iter = self.transpile_expression(iterable);
                let m_var = self.mangle_identifier(var);
                let mut result = format!("{}if let IfaValue::List(items) = {} {{\n", indent, iter);
                self.indent += 1;
                let indent2 = self.indent_str();
                result.push_str(&format!("{}for {} in items {{\n", indent2, m_var));

                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;

                result.push_str(&format!("{}}}\n", indent2));
                self.indent -= 1;
                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::Match {
                condition, arms, ..
            } => {
                let cond = self.transpile_expression(condition);
                let mut result = format!("{}let cond_val = {};\n", indent, cond);

                for (i, arm) in arms.iter().enumerate() {
                    let prefix = if i == 0 { "if" } else { "else if" };
                    let condition = match &arm.pattern {
                        MatchPattern::Literal(expr) => {
                            format!("cond_val == {}", self.transpile_expression(expr))
                        }
                        MatchPattern::Range { start, end } => {
                            let s = self.transpile_expression(start);
                            let e = self.transpile_expression(end);
                            format!("cond_val >= {} && cond_val <= {}", s, e)
                        }
                        MatchPattern::Wildcard => "true".to_string(),
                    };

                    result.push_str(&format!("{}{} {} {{\n", indent, prefix, condition));
                    self.indent += 1;
                    for s in &arm.body {
                        result.push_str(&self.transpile_statement(s));
                        result.push('\n');
                    }
                    self.indent -= 1;
                    result.push_str(&format!("{}}}\n", indent));
                }
                result.trim_end().to_string()
            }

            Statement::Return { value, .. } => {
                if let Some(v) = value {
                    format!(
                        "{}early_return = Some({}); return;",
                        indent,
                        self.transpile_expression(v)
                    )
                } else {
                    format!("{}return;", indent)
                }
            }

            Statement::EseDef {
                name,
                params,
                body,
                visibility,
                is_async,
                ..
            } => {
                let vis = self.visibility_prefix(*visibility);
                let async_kw = if *is_async {
                    self.has_async = true;
                    "async "
                } else {
                    ""
                };
                let params_str: Vec<String> = params
                    .iter()
                    .map(|p| format!("{}: IfaValue", p.name))
                    .collect();
                let mut result = format!(
                    "{}{}{}fn {}({}) -> IfaValue {{\n",
                    indent,
                    vis,
                    async_kw,
                    self.mangle_identifier(name),
                    params_str.join(", ")
                );

                self.indent += 1;
                result.push_str(&format!(
                    "{}let mut early_return: Option<IfaValue> = None;\n",
                    self.indent_str()
                ));
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                result.push_str(&format!(
                    "{}early_return.unwrap_or(IfaValue::Nil)\n",
                    self.indent_str()
                ));
                self.indent -= 1;

                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::OduDef { name, .. } => {
                // DESIGN DECISION (2026-04-07): Class-based OOP is formally removed from Ifá-Lang.
                // Both the AST interpreter and Bytecode VM already reject this syntax.
                // For native builds, we emit a hard compile_error! to prevent stale code execution.
                format!(
                    "{}compile_error!(\"Class/OOP syntax ('{}') is not supported. See ROADMAP.md §Phase 2 for migration to Map+Protocol design.\");",
                    indent, name
                )
            }


            Statement::Import { path, names, .. } => {
                if self.handle_import(path, names) {
                    format!("{}// import handled", indent)
                } else {
                    format!(
                        "{}compile_error!(\"ifa build: module imports are not supported yet\");",
                        indent
                    )
                }
            }

            Statement::Ase { .. } => {
                format!("{}std::process::exit(0);", indent)
            }

            Statement::Taboo { source, target, .. } => {
                format!("{}// TABOO: {} cannot call {}", indent, source, target)
            }

            Statement::Ewo {
                condition, message, ..
            } => {
                let cond = self.transpile_expression(condition);
                let msg = message
                    .clone()
                    .unwrap_or_else(|| "Assertion failed".to_string());
                format!("{}assert(({}).is_truthy(), \"{}\");", indent, cond, msg)
            }

            Statement::Opon { size, .. } => {
                // Emit Rust constants from the #opon directive
                let (stack_limit, frame_limit) = match size.as_str() {
                    "kekere" => ("256", "64"),
                    "arinrin" => ("4_096", "512"),
                    "nla" => ("65_536", "4_096"),
                    "ailopin" => ("usize::MAX", "usize::MAX"),
                    _ => ("4_096", "512"), // default = arinrin
                };
                format!(
                    r#"{indent}// #opon {size} — memory constraints
{indent}const IFA_OPON_STACK_LIMIT: usize = {stack_limit};
{indent}const IFA_OPON_FRAME_LIMIT: usize = {frame_limit};"#,
                    indent = indent,
                    size = size,
                    stack_limit = stack_limit,
                    frame_limit = frame_limit,
                )
            }

            Statement::Expr { expr, .. } => {
                format!("{}{};", indent, self.transpile_expression(expr))
            }

            Statement::Ebo { offering, .. } => {
                let val = self.transpile_expression(offering);
                format!(
                    r#"{}{{
    // Ẹbọ: Reactive aspect initialized
    let _ebo_state = std::sync::Arc::new(std::sync::Mutex::new({}));
}}"#,
                    indent, val
                )
            }

            Statement::Ailewu { body, .. } => {
                let mut result = format!("{}unsafe {{\n", indent);
                result.push_str(&format!(
                    "{}    // Àìléwu: Dangerous operations ahead\n",
                    indent
                ));
                self.indent += 1;
                for s in body {
                    result.push_str(&self.transpile_statement(s));
                    result.push('\n');
                }
                self.indent -= 1;
                result.push_str(&format!("{}}}", indent));
                result
            }

            Statement::Yield { duration, .. } => {
                let dur = self.transpile_expression(duration);
                format!(
                    r#"{indent}{{
{indent}    let __ifa_yield_duration = {dur};
{indent}    match __ifa_yield_duration {{
{indent}        IfaValue::Int(micros) if micros > 0 => std::thread::sleep(std::time::Duration::from_micros(micros as u64)),
{indent}        IfaValue::Int(_) => (), // jowo 0: yield immediately / no duration hint
{indent}        _ => eprintln!("Runtime Error: Yield duration must be an Int (microseconds)"),
{indent}    }}
{indent}}}"#,
                    indent = indent,
                    dur = dur
                )
            }

            Statement::Update { .. } => {
                format!("{indent}compile_error!(\"Ifá transpiler: update statements (++, --, +=, etc) are not supported yet\");", indent = indent)
            }

            Statement::Try { .. } => {
                format!(
                    "{}compile_error!(\"Ifá transpiler: gbiyanju/gba (try/catch) is not supported yet\");",
                    indent
                )
            }
        }
    }

    /// Transpile assignment target
    pub fn transpile_assign_target(&mut self, target: &AssignTarget) -> String {
        match target {
            AssignTarget::Variable(name) => self.mangle_identifier(name),
            AssignTarget::Index { name, index } => {
                format!(
                    "{}[{}]",
                    self.mangle_identifier(name),
                    self.transpile_expression(index)
                )
            }
            AssignTarget::Dereference(_) => {
                // Conformance: never crash the transpiler on valid input.
                // Emit a Rust compile-time error instead.
                "compile_error!(\"Ifá transpiler: dereference assignment (*p = v) is not supported yet\");".to_string()
            }
        }
    }

    fn prepare_imports(&mut self, program: &Program) {
        for stmt in &program.statements {
            if let Statement::Import { path, names, .. } = stmt {
                let _ = self.handle_import(path, names);
            }
        }
    }

    fn handle_import(&mut self, path: &[String], names: &Option<Vec<String>>) -> bool {
        let is_std = path.first().map(|p| p == "std").unwrap_or(false);
        if !is_std {
            return false;
        }
        let domain_name = path.last().cloned().unwrap_or_default();
        if let Some(domain) = std_domain_from_name(&domain_name) {
            if let Some(names) = names {
                for name in names {
                    self.std_named.insert(name.clone(), domain);
                }
            } else {
                let module_name = path.last().cloned().unwrap_or_else(|| "module".into());
                self.std_modules.insert(module_name, domain);
            }
            true
        } else {
            false
        }
    }
}
