//! # Project Generator
//!
//! Generates standalone Rust projects from transpiled Ifá-Lang code.
//!
//! Creates a complete Cargo project with:
//! - Cargo.toml with appropriate dependencies
//! - src/main.rs with the transpiled code

use crate::ast::Program;
use crate::transpiler::RustTranspiler;
use std::fs;
use std::io;
use std::path::Path;

/// Project configuration derived from transpiled code analysis
pub struct ProjectConfig {
    pub name: String,
    pub needs_tokio: bool,
    pub needs_reqwest: bool,
    pub needs_rand: bool,
}

impl Default for ProjectConfig {
    fn default() -> Self {
        Self {
            name: "ifa_project".to_string(),
            needs_tokio: false,
            needs_reqwest: false,
            needs_rand: false,
        }
    }
}

/// Generate a complete Cargo project from an Ifá program
pub fn generate_project(
    program: &Program,
    project_name: &str,
    output_dir: &Path,
) -> io::Result<ProjectConfig> {
    // Create directory structure
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)?;

    // Transpile the program
    let mut transpiler = RustTranspiler::new();
    let rust_code = transpiler.transpile_program(program);

    // Create project config from transpiler state
    let config = ProjectConfig {
        name: project_name.to_string(),
        needs_tokio: transpiler.needs_tokio,
        needs_reqwest: transpiler.needs_reqwest,
        needs_rand: transpiler.needs_rand,
    };

    // Generate Cargo.toml
    let cargo_toml = generate_cargo_toml(&config);
    fs::write(output_dir.join("Cargo.toml"), cargo_toml)?;

    // Write main.rs
    fs::write(src_dir.join("main.rs"), rust_code)?;

    // Generate .gitignore
    let gitignore = "/target\nCargo.lock\n";
    fs::write(output_dir.join(".gitignore"), gitignore)?;

    Ok(config)
}

fn generate_cargo_toml(config: &ProjectConfig) -> String {
    let mut deps = Vec::new();

    if config.needs_tokio {
        deps.push("tokio = { version = \"1\", features = [\"full\"] }");
    }

    if config.needs_reqwest {
        deps.push("reqwest = { version = \"0.12\", features = [\"blocking\"] }");
    }

    if config.needs_rand {
        deps.push("rand = \"0.8\"");
    }

    let deps_str = if deps.is_empty() {
        String::new()
    } else {
        format!("\n{}", deps.join("\n"))
    };

    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

# Generated by Ifá-Lang Transpiler
# Àṣẹ - May it be so

[dependencies]{deps_str}

[profile.release]
opt-level = 3
lto = true
"#,
        name = config.name,
        deps_str = deps_str
    )
}

/// Expose RustTranspiler fields for project generation
impl RustTranspiler {
    pub fn needs_tokio(&self) -> bool {
        self.needs_tokio
    }

    pub fn needs_reqwest(&self) -> bool {
        self.needs_reqwest
    }

    pub fn needs_rand(&self) -> bool {
        self.needs_rand
    }
}
